version: '3'
services:
  mockallan:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile
    image: mockallan-latest
    tty: true
    stdin_open: true
    environment:
      - MOCKALLAN_PORT=8080
    ports:
      - "8080:8080"
